on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  CItesting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.7"
      - name: Install CI test dependencies
        shell: bash -l {0}
        run: |
          conda info
          conda env create -p conda
      - name: Run CI tests
        shell: bash -l {0}
        run: |
          conda activate conda/
          pytest
    
